travis:
  secure:
    BINSTAR_TOKEN: b6G93nyGiIFIgYLpdRd8uYqkeSK7gg/LbUcv5K5u4lLvTApu6QEZgJuL3VrFHfImEvAyW0fKd+7XOHyPP5Yt0aOOHbS2CaN/eDwF5cZOLCJxORHE7/2K6wJimjclIS5yvhkBu29Qr17Ps9Z8CgLFcteLc7R01UJcxqmHiIu2qBfHDuT6C31dpzi7pCWktj52cLv+PB32PtN07OkHfEYqenIDmnB3x7amPYjXIPEi8pg53ivzUzn4ZyYAI6H+6Ss8sR9ZmPMIGSmIk6sqyejlCqdifMeR6MgB92m/aGr/nI3iAHXTsaowqcZokUSgfuw4xKTMNUYqLk1u6QvRkul6lRtJ/eeOMH0gFlXP/a+JbpMskp5IYkk1ekIVFoVRE+p2LPGfv4liSxbDszXpJk4izNGg+ipib+f9RUsQBwubLBOKZ6F7AfF2C3eLYB297MFowPDL2pRRtuzxYvkyrbc1GIVT50o0iR4FmGKhYsj0ZEfZ9wjKtqGxtf+/vCbbFBPKHtrn/gCVWODBvhuH6XeSq9ZQttYcDEhPXx+hzR80e7iASNfqs+urAPbzKCGwEjpfUfXZBK3syYwtedEPK8JwPn6r4CFpi5dwhg26aIKy4lsVUX/hEEWJo/szQNkS8rquePsWq2qQpbvsnGUQeo90NmNZGXqyfLjsm9lmUG4vfqE=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
